vscode:
  extensions:
    - mjmcloug.vscode-elixir@1.1.0:w8GjsJyyhVFmCZmBc2Ws7A==
image:
  file: gitpod.Dockerfile
tasks:
  - command: npm install --prefix apps/mam_web/assets && cd apps/mam_web && mix local.hex --force && mix deps.get && mix local.rebar --force && mix phx.server
    name: web server
    openMode: tab-after
ports:
  - port: 4000
    onOpen: open-browser
